/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWbRouteImport } from './routes/dashboard/wb'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardPlayerIndexRouteImport } from './routes/dashboard/player/index'
import { Route as DashboardPlayerLessonIdRouteImport } from './routes/dashboard/player/$lessonId'
import { Route as DashboardPracticeIndexRouteImport } from './routes/dashboard/practice/index'
import { Route as DashboardPracticeLessonIdRouteImport } from './routes/dashboard/practice/$lessonId'
import { Route as DashboardProgressIndexRouteImport } from './routes/dashboard/progress/index'
import { Route as DashboardStatsIndexRouteImport } from './routes/dashboard/stats/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWbRoute = DashboardWbRouteImport.update({
  id: '/wb',
  path: '/wb',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayerIndexRoute = DashboardPlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlayerLessonIdRoute = DashboardPlayerLessonIdRouteImport.update({
  id: '/player/$lessonId',
  path: '/player/$lessonId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPracticeIndexRoute = DashboardPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPracticeLessonIdRoute =
  DashboardPracticeLessonIdRouteImport.update({
    id: '/practice/$lessonId',
    path: '/practice/$lessonId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProgressIndexRoute = DashboardProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStatsIndexRoute = DashboardStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/wb': typeof DashboardWbRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/player/$lessonId': typeof DashboardPlayerLessonIdRoute
  '/dashboard/practice/$lessonId': typeof DashboardPracticeLessonIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/player/': typeof DashboardPlayerIndexRoute
  '/dashboard/practice/': typeof DashboardPracticeIndexRoute
  '/dashboard/progress/': typeof DashboardProgressIndexRoute
  '/dashboard/stats/': typeof DashboardStatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/wb': typeof DashboardWbRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/player/$lessonId': typeof DashboardPlayerLessonIdRoute
  '/dashboard/practice/$lessonId': typeof DashboardPracticeLessonIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/player': typeof DashboardPlayerIndexRoute
  '/dashboard/practice': typeof DashboardPracticeIndexRoute
  '/dashboard/progress': typeof DashboardProgressIndexRoute
  '/dashboard/stats': typeof DashboardStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/wb': typeof DashboardWbRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/player/$lessonId': typeof DashboardPlayerLessonIdRoute
  '/dashboard/practice/$lessonId': typeof DashboardPracticeLessonIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/player/': typeof DashboardPlayerIndexRoute
  '/dashboard/practice/': typeof DashboardPracticeIndexRoute
  '/dashboard/progress/': typeof DashboardProgressIndexRoute
  '/dashboard/stats/': typeof DashboardStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/wb'
    | '/dashboard/'
    | '/dashboard/player/$lessonId'
    | '/dashboard/practice/$lessonId'
    | '/dashboard/admin/'
    | '/dashboard/player/'
    | '/dashboard/practice/'
    | '/dashboard/progress/'
    | '/dashboard/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/wb'
    | '/dashboard'
    | '/dashboard/player/$lessonId'
    | '/dashboard/practice/$lessonId'
    | '/dashboard/admin'
    | '/dashboard/player'
    | '/dashboard/practice'
    | '/dashboard/progress'
    | '/dashboard/stats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/wb'
    | '/dashboard/'
    | '/dashboard/player/$lessonId'
    | '/dashboard/practice/$lessonId'
    | '/dashboard/admin/'
    | '/dashboard/player/'
    | '/dashboard/practice/'
    | '/dashboard/progress/'
    | '/dashboard/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wb': {
      id: '/dashboard/wb'
      path: '/wb'
      fullPath: '/dashboard/wb'
      preLoaderRoute: typeof DashboardWbRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/player/': {
      id: '/dashboard/player/'
      path: '/player'
      fullPath: '/dashboard/player/'
      preLoaderRoute: typeof DashboardPlayerIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/player/$lessonId': {
      id: '/dashboard/player/$lessonId'
      path: '/player/$lessonId'
      fullPath: '/dashboard/player/$lessonId'
      preLoaderRoute: typeof DashboardPlayerLessonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/practice/': {
      id: '/dashboard/practice/'
      path: '/practice'
      fullPath: '/dashboard/practice/'
      preLoaderRoute: typeof DashboardPracticeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/practice/$lessonId': {
      id: '/dashboard/practice/$lessonId'
      path: '/practice/$lessonId'
      fullPath: '/dashboard/practice/$lessonId'
      preLoaderRoute: typeof DashboardPracticeLessonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/progress/': {
      id: '/dashboard/progress/'
      path: '/progress'
      fullPath: '/dashboard/progress/'
      preLoaderRoute: typeof DashboardProgressIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stats/': {
      id: '/dashboard/stats/'
      path: '/stats'
      fullPath: '/dashboard/stats/'
      preLoaderRoute: typeof DashboardStatsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardWbRoute: typeof DashboardWbRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPlayerLessonIdRoute: typeof DashboardPlayerLessonIdRoute
  DashboardPracticeLessonIdRoute: typeof DashboardPracticeLessonIdRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardPlayerIndexRoute: typeof DashboardPlayerIndexRoute
  DashboardPracticeIndexRoute: typeof DashboardPracticeIndexRoute
  DashboardProgressIndexRoute: typeof DashboardProgressIndexRoute
  DashboardStatsIndexRoute: typeof DashboardStatsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardWbRoute: DashboardWbRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPlayerLessonIdRoute: DashboardPlayerLessonIdRoute,
  DashboardPracticeLessonIdRoute: DashboardPracticeLessonIdRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardPlayerIndexRoute: DashboardPlayerIndexRoute,
  DashboardPracticeIndexRoute: DashboardPracticeIndexRoute,
  DashboardProgressIndexRoute: DashboardProgressIndexRoute,
  DashboardStatsIndexRoute: DashboardStatsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
